# Generated by Django 3.0.7 on 2020-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('heroku_id', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
