# Generated by Django 3.0.7 on 2020-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_people_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heroku_id', models.CharField(max_length=45)),
                ('films', models.ManyToManyField(to='films_people_list.Film')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
